### ISSUE TITLE
Discussion of the implementation of OTT

### ISSUE THREAD

**Issue by Diet-Cola** [CivMC/SimpleAdminHacks#52]
Just wanted to create this issue here as a centralised meaning of how we want to implement OTT to fit the goals of CivMC but also the wider usages of this feature for other civ servers.  

My following questions are: 

- How should we implement the commands? e.g /ott <player> vs /ott request <player> etc
- Should you be able to request an OTT to offline players?  Persistence etc  
- Would any restrictions be ideal to implement, e.g item blacklist that are removed from inventory when ott'd or a expiration date of usage of OTT

**Comment by Longboyy** [comment]
> How should we implement the commands? e.g /ott vs /ott request etc
I think something of the nature `/ott Longboyy` to request a teleport, and something like `/ottaccept` to accept a teleport request.

>Should you be able to request an OTT to offline players? Persistence etc
Don't really view this as a necessary thing to implement - both players should be online when one is teleporting to the other IMO

> Would any restrictions be ideal to implement, e.g item blacklist that are removed from inventory when ott'd or a expiration date of usage of OTT
I don't think an item blacklist is necessary, although there should be a (configurable) time limit on the teleport. For example a player may only be able to OTT to someone within 48 hours of joining the server.

**Comment by Gjum** [comment]
It's also an option to call the commands `/tpa <player>` and `/tpaccept [player]` -- that's what new players (target audience!) are already used to. It doesn't have to work all the time like on other servers, it just has to be familiar and work for our purposes of keeping players engaged with the server they just joined.

No offline players. The only non-abuse situation I can imagine where this could be useful at all is when you want to tp to a friend who has just been association banned.

An expiration date is annoying but helps prevent abuse. 48h are a good balance and easy to implement.

Something people complained about on Realms is being able to teleport players into areas they aren't allowed inside of, e.g. CivCorp, but this can be implemented later if it actually turns out to be an issue, and people already randomspawn in vaults etc anyway.

Item restrictions might help a bit with abuse, but are ultimately counter-intuitive -- you really want to keep the items you spent your first hours of the server gathering. If anything they would have to be end-game materials that you could only have gotten from somebody who knows about the item restrictions.

**Comment by Metriximor** [comment]
Do we need ott? I see this as a very easily exploitable mechanic, while also not bringing much to the table. A lot of nations grow because newfriends spawn in them and they join that nation since it's right there. If this were to change to OTT I feel like the newfriends would just see nation ads and tp to the bigger ones to the detriment of everyone else.

As for the commands I agree with gjum's suggestion, tpa and tpaccept is what everyone knows, no need to reinvent the wheel.

**Comment by Diet-Cola** [comment]
I think there's a strong enough support for adding OTT into SAH as it would be used outside of just here, I think the more we can add together here vs splitting off in different branches is productive and allows everyone some options. 

As for OTT on CivMC, we wanted to run stats on its usage post launch, to provide concrete data on the effects of OTT. 

Majorly agree on the tpa and tpaccept commands too
